# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /db

COPY db/mercari.sqlite3 mercari.sqlite3

WORKDIR /python

COPY python/requirements.txt requirements.txt
COPY python/main.py main.py

RUN pip3 install -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000"]